version: '3'
networks:
  db:
    external:
      name: db
services:
  backend:
    build: .
    ports:
      - '${API_PORT}:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    networks:
      - db
