version: '3'
networks:
  default:
    external:
      name: db
services:
  frontend:
    build: ../paneles-solares-frontend
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always

  backend:
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - SECRET=${SECRET}
    restart: always

  nginx:
    image: nginx
    volumes:
      - './nginx/sites_enabled/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/sites_enabled/default.template:/etc/nginx/conf.d/default.template'
    ports:
      - '${PORT}:80'
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
